# Generated by Django 3.1.6 on 2021-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=50, verbose_name='Department Name')),
            ],
        ),
    ]
