# Generated by Django 3.1.6 on 2021-03-04 16:16

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepakblog', '0002_auto_20210207_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='productDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='productProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
