# Generated by Django 3.1.6 on 2021-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepakblog', '0004_bookmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmaster',
            name='bookDescription',
            field=models.CharField(max_length=2500, verbose_name='Book Description'),
        ),
    ]
