# Generated by Django 3.1.6 on 2021-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepakblog', '0006_auto_20210327_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmaster',
            name='price',
            field=models.IntegerField(default='20', max_length=7, verbose_name='Price Of The Book'),
        ),
    ]
